### PR TITLE
Changed achievement name to It's lonely at the top

### PR DESCRIPTION
**Pull request by ExposedGun316**

### CODE REVIEW

**Comment by Kruithne** [comment]
Don't change the name of the class, keep that as MasterFighter. There's no need to change classes once they're already made.

The title of the achievement should be capitalized properly too.

**Comment by Kruithne** [comment]
Looking better, just need to fix the capitalization of the achievement name. "It's Lonely at the Top"

**Comment by ExposedGun316** [comment]
For something this easy, I seemed to have over complicated it :P

**Comment by Kruithne** [comment]
I'm super-picky about stuff, you'll learn that quickly. Speaking of which "at" and "the" shouldn't be with capitals. Do it like I did above. :)

**Comment by ExposedGun316** [comment]
It's done.

**Pull request merged**
